version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: literalura-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
